name: "GitHub Action for deploying on Oikos static"
description: "Allows deploying and managing on Nife"
author: Nife
branding:
  icon: "upload-cloud"
  color: "blue"
runs:
  using: "docker"
  image: "Dockerfile"
