name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker tag'
        required: true
      push_to_docker_hub:
        description: 'Push to Docker Hub?'
        required: true
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      if: ${{ github.event.inputs.push_to_docker_hub == 'true' }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: ${{ secrets.DOCKER_USERNAME }}/synckai:${{ github.event.inputs.tag }}
        push: ${{ github.event.inputs.push_to_docker_hub }}

